### ISSUE TITLE
2024_07 Need for MTL 3.7 release 2024_may_epic #story_b: TEST Team Setup within Sim UI

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3154]
testing functionality & design of: Administrator Dashboard > Settings > Team Setup > Add > Add

## AC:
All feedback to DEV is addressed and/or incorporated for:
- [x] Add Team Members pop-up(s)
- [x] possible other pop-up revisions as testing is performed

**Comment by ljmoody** [comment]
@tejaspesquare, within the Team Setup > Add > Add > Setup - Add Members pop-up:

- [ ] When users select and delete Team Member(s), please add functionality of a confirmation message-like the one below-before deletion occurs. Currently there is no confirmation, members are deleted immediately upon pressing the Delete button:
![image](https://github.com/lzim/teampsd/assets/124643236/a9e698b9-a733-44b3-a359-1ec7db2451ea)

- [ ] This can be explained further in the next standup meeting. We would like to change permission names to the ones we use as standard (vs Epicenter's):
![image](https://github.com/lzim/teampsd/assets/124643236/f58e9f64-df0d-4eab-956b-9a6289ab0af7)

**Comment by tejaspesquare** [comment]
@ljmoody - We have made changes as per above notes. It is available on Test-slow.

![image](https://github.com/lzim/teampsd/assets/144898781/d5615ab3-7de0-4df9-b0ba-2017ec76cfc9)

![image](https://github.com/lzim/teampsd/assets/144898781/500a34f8-40d9-4aac-ada1-ff219b3a6b99)

**Comment by ljmoody** [comment]
### 6/11/24 testing in DEV environment:
✅ validated confirmation message added when deleting team member(s) from EXISTING groups.
✅ When creating a NEW team and when editing an EXISTING team, the "Select Permissions" dropdown _does_ include correct nomenclature:
![image](https://github.com/lzim/teampsd/assets/124643236/016619a4-32a0-4038-b032-29f26c354550) 

### FYI @tejaspesquare 
Some things I noticed when testing:

- [ ] 1. When deleting a member in a newly created team (as setup is happening), the team member is deleted immediately. Suggest adding a confirmation message ("Are you sure you want to delete selected Team Member(s)?" to this as well.

- [ ] 2. Within Administrator Dashboard > Settings > Facility Team Setup > Add, please make these two changes:
    - [ ] Capitalize A in Administrator
    - [ ] Have the Permissions column reflect permissions chosen for Members as "Member" (vs Player)
![image](https://github.com/lzim/teampsd/assets/124643236/a41b0a94-b1fc-415a-a65d-50b8110fe7af)

- [ ] 3. When testing today, I created two new teams. Neither are showing up in the Team Setup list - nor after logging out/back in again:
![image](https://github.com/lzim/teampsd/assets/124643236/62cee2c4-c00f-4e22-a485-717d0496e86a)

**Comment by tejaspesquare** [comment]
Hello @ljmoody 


> * [ ]  3. When testing today, I created two new teams. Neither are showing up in the Team Setup list - nor after logging out/back in again:
>   ![image](https://private-user-images.githubusercontent.com/124643236/338734139-62cee2c4-c00f-4e22-a485-717d0496e86a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzIwMDcsIm5iZiI6MTcxODE3MTcwNywicGF0aCI6Ii8xMjQ2NDMyMzYvMzM4NzM0MTM5LTYyY2VlMmM0LWMwMGYtNGUyMi1hNDg1LTcxN2QwNDk2ZTg2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwNTU1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjQ5MTM1YjgzZTZlNTY3N2IwMGY0MTE0NjllN2ZmNTdjZWM5NDM2MjI1MWFkODc0ZjIzZmUyNmIxZGI4YTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Clw46T8ITPYFSgzCaHWBcnNZSO636R3WnlVFIbp3cuo)

Kindly provide the names of the teams for further investigation, if you have stored or remember it. We are able create a new team successfully.

SIM UI
![image](https://github.com/lzim/teampsd/assets/144898781/9dea26de-db35-4886-ba78-633d3095a2f8)
Epicenter-
![image](https://github.com/lzim/teampsd/assets/144898781/e534fa93-267a-4542-9b80-8e432339bfae)

**Comment by tejaspesquare** [comment]
Hello @ljmoody,
Changes accommodated as per below points.
> 
> * [ ]  1. When deleting a member in a newly created team (as setup is happening), the team member is deleted immediately. Suggest adding a confirmation message ("Are you sure you want to delete selected Team Member(s)?" to this as well.
> * [ ]  2. Within Administrator Dashboard > Settings > Facility Team Setup > Add, please make these two changes:
>   
>   * [ ]  Capitalize A in Administrator
>   * [ ]  Have the Permissions column reflect permissions chosen for Members as "Member" (vs Player)


![image](https://github.com/lzim/teampsd/assets/144898781/91a106cc-3dd4-4074-bad1-ddeb9359942d)

![image](https://github.com/lzim/teampsd/assets/144898781/d6cc1580-f576-4607-8b42-fb2443ebb9ad)

**Comment by ljmoody** [comment]
## Testing in TEST-slow
- Verified Points 1 & 2 above have been addressed.
- @tejaspesquare, please disregard Point 3 above. Upon reflection, the teams I made were likely never fully "created" because the processing three dots kept going for minutes, then I refreshed the screen. I tested this functionality again today and it is working as expected. Considering this point verified and a non-issue. 
- [ ] 4. When adding an individual to a team as its being created, and forgetting to input their email, the following message was observed. Please change message to "Email is required."
![image](https://github.com/lzim/teampsd/assets/124643236/ab263e05-947f-4336-b114-62a974f84ca1)

- [ ] 5. While creating a team and adding members, if a team member name is selected, then Setup - Add Members "Edit" button is pressed, the First Name and Last Name fields are not populated (even though they were input as shown on the team list). These fields should be populated as they were upon setup. In this example, the First Name field should show "Cherry" and the Last Name field should show "Croissant":
![image](https://github.com/lzim/teampsd/assets/124643236/ea3a4a37-6123-4f12-a124-38144bae5b98)

- [ ] 6. Within Settings > selecting a team and clicking "Edit" button > selecting an automatically added SME, then clicking "Edit" button, the First Name and Last Name fields are not populated:
![image](https://github.com/lzim/teampsd/assets/124643236/c67aff81-e43d-43d8-b070-eb2ead64a4e9)

- [ ] 7. Logged in with VA account, I created june12_laura_testing teams (_team, _ind, & _shared). I added my Praxis email only to _team as a Lead, as shown below:
![image](https://github.com/lzim/teampsd/assets/124643236/4f845f06-afb8-4211-b4fb-2910754d6eb3)
I then logged out and logged in using Praxis account - and see these teams:
![image](https://github.com/lzim/teampsd/assets/124643236/376e0fb2-a9c0-45be-a861-894580b02dfb)
I don't think I should be seeing the _ind team here given the setup of the teams shown above - correct?

FYI: @jamesmrollins

**Comment by tejaspesquare** [comment]
Hello @ljmoody, Points 5 & 6 this are being handled & can be tested on Test-slow.

> * [ ]  5. While creating a team and adding members, if a team member name is selected, then Setup - Add Members "Edit" button is pressed, the First Name and Last Name fields are not populated (even though they were input as shown on the team list). These fields should be populated as they were upon setup. In this example, the First Name field should show "Cherry" and the Last Name field should show "Croissant":

![image](https://github.com/lzim/teampsd/assets/144898781/8fdf7107-2227-4487-9d28-71c288b0f942)


> * [ ]  6. Within Settings > selecting a team and clicking "Edit" button > selecting an automatically added SME, then clicking "Edit" button, the First Name and Last Name fields are not populated:

Added - SME
![image](https://github.com/lzim/teampsd/assets/144898781/6e1aee57-fc8c-4142-b6fb-8b1018c301f7)

Edit
![image](https://github.com/lzim/teampsd/assets/144898781/9a17e6f9-f476-4d09-a4d6-95351a1d3f64)

**Comment by tejaspesquare** [comment]
> * [ ]  7. Logged in with VA account, I created june12_laura_testing teams (_team, _ind, & _shared). I added my Praxis email only to _team as a Lead, as shown below:
>   ![image](https://private-user-images.githubusercontent.com/124643236/339109521-4f845f06-afb8-4211-b4fb-2910754d6eb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzcxOTAsIm5iZiI6MTcxODI3Njg5MCwicGF0aCI6Ii8xMjQ2NDMyMzYvMzM5MTA5NTIxLTRmODQ1ZjA2LWFmYjgtNDIxMS1iNGZiLTI5MTA3NTRkNmViMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxMTA4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjU2NjBjOTBkYWQzODkwZTI5N2QyN2MwYWExYjIwMGQxMGM2ZWQ4NTlmMzI2MTQwZjk5MmQ5ZjJiYzI0Y2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.krJxU13ZDDHBqSPgUqbyoCDRroKfQiUIxiEPR_Bzi70)
>   I then logged out and logged in using Praxis account - and see these teams:
>   ![image](https://private-user-images.githubusercontent.com/124643236/339110921-376e0fb2-a9c0-45be-a861-894580b02dfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzcxOTAsIm5iZiI6MTcxODI3Njg5MCwicGF0aCI6Ii8xMjQ2NDMyMzYvMzM5MTEwOTIxLTM3NmUwZmIyLWE5YzAtNDViZS1hODYxLTg5NDU4MGIwMmRmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QxMTA4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmFkMTQxNTdjOGIxZWFkZTNjMWI4ZjRmYTJjY2E3YTg2ZWViZTBkZmRjNmM0ZTYxMTViMTBlY2MyYzM5N2U0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9MQP8j7uGQRc08aPfN-Ssp8UYOxqhmyWlRp_e_J_PL4)
>   I don't think I should be seeing the _ind team here given the setup of the teams shown above - correct?


Based on our monitoring, there have been no modifications made to this feature since its development. The current behavior is as follows:
After the initial setup of teams (_team, _shared, & _ind):
i. Adding a member to _team will automatically add them to _shared and _ind.   For this reason, _ind also listed in drop-down.   
ii. Adding a member to _shared will not affect _ind or _team.
iii. Adding a member to _ind will not impact _team or _shared.

If there are any anticipated changes to this behavior, please inform us accordingly we will work on it.

Just to note & may not relevance here - in Jan'24 we worked on Team setup world issues for ind, shared, team worlds through card #3061.

**Comment by lzim** [comment]
#systems_sme_workflow 

@ljmoody 
@tejaspesquare 
Working to set up [#572](https://github.com/lzim/research/issues/572)
- [ ] 01. I am no longer seeing "facilitator" in the drop down, which is great! 😃 But, I am see still seeing a random assortment of my teams in the dropdown when I login (not shown, exactly).

![image](https://github.com/lzim/teampsd/assets/7454688/917e0aad-2e35-4ea8-943b-939e74230e09)

- [ ] 02. I used the Facility Team Setup but it only set up a _shared world no _team or _ind

![image](https://github.com/lzim/teampsd/assets/7454688/51053c24-aa31-4c18-b855-f01be277ce00)

**Comment by ljmoody** [comment]
@lzim, 

Regarding your point 2 above, I'll conduct testing today to see if I get the same result and comment in this card with what I find.

Regarding your point 1 above, my hunch is that your _random assortment of my teams in the dropdown when I login_ has to do with permissions.

Tejas offered this explanation for why you see teams in this login dropdown:
> It is normal to observe the presence of certain teams on the world selection dropdown when you log in. This occurrence is expected because you do not possess the Facilitator role (on Epicenter) for those particular groups. 

See his post + Epicenter screenshot on card #3181 from a few days ago.

Additional FYIs about how the system is handling permission functionality:
-  If you hold the Administrator role in any group, along with added into 'administrator_login' on Epicenter,
   - You will be allowed to login as 'administrator_login' world.
   - Otherwise, it will load teams & on selection you will be redirected to Home screen & bypassing the Dashboard.
- Teams under Settings -> Facility Team Setup:
   - When you log in, only the teams that you have joined and have the 'Administrator' role will be shown.
   - 'Lead' & 'Member' permissions teams won't be visible for logged in user.

So, I would recommend checking
- [ ] Your Epicenter role(s) for the teams you see in your login dropdown - if you aren't listed as a Facilitator for these groups, then the system is behaving as expected. If you **are** listed as Facilitator, please take a screenshot, post here, tag Tejas, and he/James can investigate. 

FYI: @jamesmrollins

**Comment by ljmoody** [comment]
@lzim and @tejaspesquare,
Regarding Lindsey's point 2 above: **I used the Facility Team Setup but it only set up a _shared world no _team or _ind**

I tested this functionality in PROD today by creating a team, adding members, and upon clicking "Done", the team with three world extensions were created - and contain all 6 auto-added individuals:
![image](https://github.com/lzim/teampsd/assets/124643236/42a1480c-dcb3-46cb-a7ac-878a353e325f)

- [ ] @lzim, please try clearing your cache to see if the problem still persists and let us know if that changes anything.

In the meantime,
- [ ] @tejaspesquare, I do see that all 3 worlds were created for this team (via Epicenter). However, not all teams created contain the same auto-added members. Hypothesis is that something in the code is not correct. See screenshots below for more detail:
![image](https://github.com/lzim/teampsd/assets/124643236/a5e2ee85-dc2c-4710-a0ee-014158910355)

fyi @jamesmrollins

**Comment by tejaspesquare** [comment]
Hello @ljmoody 

> * [ ]  @tejaspesquare, I do see that all 3 worlds were created for this team (via Epicenter). However, not all teams created contain the same auto-added members. Hypothesis is that something in the code is not correct. See screenshots below for more detail:

This function operates flawlessly in our account & all teams got created with same auto-added members as expected.  We have verified by setup of 2 teams on 13th June & 14th June respectively, i.e. 'devqatest_14june' & 'devqatest_13june'.

Auto added members-
![image](https://github.com/lzim/teampsd/assets/144898781/8dbcbd91-c7f7-48a2-ae37-7b266b7ade92)

![image](https://github.com/lzim/teampsd/assets/144898781/10bad732-84ff-42fa-b040-2641dae10f61)

**Comment by ljmoody** [comment]
@tejaspesquare, appreciate you showing what you see on your end. This is indeed a curious thing to happen! Trying to unravel this below:

**Given what Tejas said/showed above, I tested today by:**
1. Logging into PROD using Lindsey's credentials.
2. Created a new team via Settings > Facility Team Setup.
3. Team was successfully created and all 3 worlds of this team appear in the team list:
![image](https://github.com/lzim/teampsd/assets/124643236/5e8daeae-cd5f-4872-97db-f06241a96a7d)
4. I checked members within each team, and all 6 auto-added members are there:
![image](https://github.com/lzim/teampsd/assets/124643236/13b46f67-e3ed-461b-8bb9-20061734e0bc)

So by my testing and experience today, this is working correctly. However, it still doesn't solve the mystery about why Lindsey created a team and cannot see all worlds. 

@lzim, I am going to manually add you (via Epicenter) to the blue CBOC team you created yesterday, in both _team and _ind worlds. That should take care of that team's visibility issues for you.
- [ ] ▶️ To help us troubleshoot, I need you to log into PROD, clear your cache, then create a new team again and share your results here. 

fyi @jamesmrollins

**Comment by lzim** [comment]
#sim_ui_workflow - Please add story point estimates.
Thx!

**Comment by lzim** [comment]
**_Can I confirm the Team Setup is in PROD now?_**
_Shoudl this be closed?_

**Comment by ljmoody** [comment]
Tested using Edge.
✅ verified points 4, 5
✅ verified that all 3 worlds were created for a new team that was made

@tejaspesquare:
- [ ] Please revise this error message:
![image](https://github.com/user-attachments/assets/e0d1cb16-1321-4234-83b2-0099d2a21d98)

- [ ] When trying to verify point 6 above, I could not because newly created team only had these members upon creation:
![image](https://github.com/user-attachments/assets/65949106-dab6-48e5-a985-a081124a75de)

**Comment by tejaspesquare** [comment]
Hello @ljmoody 

Changes incorporated for point1.

> * [ ]  Please revise this error message:
![image](https://github.com/user-attachments/assets/d57c6b5a-1b68-46ab-a867-52b55146bdb9)


> * [ ]  When trying to verify point 6 above, I could not because newly created team only had these members upon creation:

We can discuss this further during our next meet.

**Comment by lijenn** [comment]
Discussed 7/19:
- [ ] @matomasz will discuss this with @tejaspesquare, loop in @ljmoody and/or @lijenn if needed

**Comment by matomasz** [comment]
Discussed 7/22 Dev Standup Call:

- @tejaspesquare will test to see if SME first and last names are populating correctly on local test environment 
- @matomasz will try to set up a team to help diagnose the cause of the issue where not all default members are being added to a team

**Comment by ljmoody** [comment]
8/2/24 update from Tejas: 
- Code migrated from DEV to TEST environment. Ready to test. 
fyi: @lijenn @matthewtomo

**Comment by matthewtomo** [comment]
**Tested 8/5/2024** On non VA Machine
- It appears that the Edit Members popup now properly loads in the member names.
- These changes appear to be ready for PROD

## Chrome:
![image](https://github.com/user-attachments/assets/d2bc4e6a-665b-4ecc-8327-f3d71a0309c9)

## Edge:
![image](https://github.com/user-attachments/assets/b5bdfcfe-32d0-4db0-8c0d-aace9145e7f2)

fyi: @tejaspesquare @ljmoody @lijenn

**Comment by matthewtomo** [comment]
**Discussed 8/20/24**

Fix for this issue has been completed and pushed to PROD.
