### ISSUE TITLE
1.7.3 SP Module Update

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#320]
This thread is being started to isolate and disposition SP Model issues.

**Comment by jamesmrollins** [comment]
**Version 1.7.3 is in TEST**: Please consult the design summary below, review the checklist below to and indicate your "Go, No-Go" response. Participants are in a test group named "version_1_7_to_1_8_test" and assigned individual worlds. I have truncated the checklist to only cover things that are applicable for this sprint.

**Design Summary:** The SP Module was:

1. Updated with gaming variables to allow for time stepping.

**Simulation Run** (James and Tom)

* [x]     1. Widgets return same values as the client version of Vensim.
* [x]     2. Charts are consistent with values from the client version of Vensim.

**Training and Documentation** (Debbie, Jane, and Stacey)

* [ ]     1. Changes in simulation are noted in training documents, or are in process.
* [ ]     2. Changes are consistent with dialogue and instruction in current video training.
* [ ]     3. Help descriptions are up-to-date and include explanations of new functions or variables.
* [ ]     4. "i" Information is up-to-date, correct and complete.

**Comment by lzim** [comment]
Thanks @jamesmrollins !!

**Comment by branscombj** [comment]
![image](https://user-images.githubusercontent.com/29778290/53582096-d6465e80-3b4c-11e9-80c1-da3de4c425c1.png)

**Comment by lzim** [comment]
I'm not sure what the issue is, maybe @jamesmrollins can help.
@branscombj  what world are you selecting here?

![image](https://user-images.githubusercontent.com/7454688/53676314-54fbe280-3c98-11e9-97eb-ada85722325d.png)

- Should be 
![image](https://user-images.githubusercontent.com/7454688/53676332-97252400-3c98-11e9-958c-c43cc275bc07.png)

Right @staceypark ?

Thanks!

**Comment by saveth** [comment]
@jamesmrollins @holbrooa @TomRust @lzim @staceypark 

I need some clarification on the SP module. In 1.7.3 test the Team Data Table indicates that New Patient Start Rate is median, but the ModelParameters file says mean-- the master crosswalk has both measurements.

![image](https://user-images.githubusercontent.com/12439059/53992608-1922ac00-40e2-11e9-8248-8dd6d872da30.png)

![image](https://user-images.githubusercontent.com/12439059/53993050-24c2a280-40e3-11e9-9ca8-9568ea4f75ad.png)

![image](https://user-images.githubusercontent.com/12439059/53993089-3dcb5380-40e3-11e9-9d85-29819824458a.png)

Which metric are we using? Median or mean?

**Comment by jamesmrollins** [comment]
Hi @saveth , I reviewed the model and found that there isn't a "Data XXX New Patient Start Rate." I think that it is a calculated value, vice an import from the team data table (see below).  @TomRust will have to answer whether is a mean or a median.

![image](https://user-images.githubusercontent.com/30132017/53993595-b383ef00-40e4-11e9-85da-0f599e46a2ca.png)

**Comment by TomRust** [comment]
@jamesmrollins , @saveth, @holbrooa --

I don't really know which it is/should be.  It doesn't matter to the model if its a mean or a median.  I figure Andrew can weigh in on what calculation we do most often for these rates in our other models.

Sorry I can't be more decisive/helpful,  :)
--TOM

**Comment by jamesmrollins** [comment]
Hi James,

Now that Andrew is back, we’ve talked through the SP data, and come up with a few minor changes to make to the team data table in the Sim UI.

1)	There are two typos (underlined in red) – “Hish Risk patients” should read “High Risk Patients”
2)	In the Stepped Care section of the table, the word “Inpatient” should be replaced with “Residential”
3)	The specific cells might change, now that we changed the definition, so I’m letting Andrew tell you which cells go to which spots in the data table (hand labeled A through F).  They might be all the same, but I wanted to let him weigh in.
4)	The text in the team data popup will have to change, too.  We’ll just put that in the crosswalk table on OSF.
![image](https://user-images.githubusercontent.com/30132017/54451604-720cc880-4710-11e9-90d7-d225df286a16.png)

**Comment by jamesmrollins** [comment]
Record of conversation with @TomRust:

The Team Data Table in the Experiment section does not need any changes.  All six data points concerning patients going to residential (flagged or not) in the excel table are in the Data Table in the UI. 
However, all instances of "Inpatient" should still be replaced with "Residential."

**Comment by TomRust** [comment]
Hi @jamesmrollins -- you probably thought about this already...but I wanted to make sure: Since we're changing variable names in the team data table and the model diagram, we need to change the variable drop-down list for the charts in the Extended Outputs section to match.

**Comment by jamesmrollins** [comment]
Hi @TomRust, I was only aware of the changes to the table, and by extension the charts.  I am not aware of the need to change all instances in the sim UI.  Did you mean chasing down all instances of "inpatient" in the sim UI?  If so, that is a pretty major undertaking . . . 

![image](https://user-images.githubusercontent.com/30132017/54764744-99064700-4bb5-11e9-84da-b3d7d27b2fa4.png)

**Comment by TomRust** [comment]
Sorry, @jamesmrollins !  Yes, all the labels that used to say "...Residential or Inpatient" need to be relabeled as just "...Residential"

For each setting there should now be only one rate that has "Inpatient" in the title -- the green inflow for patient returning from Inpatient.  Those are fine as is.  

GMH example below:
![image](https://user-images.githubusercontent.com/32961420/54766425-a03b4e00-4bd1-11e9-9844-3b877d744c6e.png)

**Comment by jamesmrollins** [comment]
@TomRust Then we should also chase these changes all the way through to the Vensim and the Model Crosswalk table to maintain consistency. With your permission, I will chase those down and send you an updated SP Vensim for your review and upload into GitHub.

**Comment by holbrooa** [comment]
Tom and Andrew have been working through the Time to Improve issue in the SP model/query. The issue is: the data pull uses retroactive logic to assign patients to high or low symptom groups, but the model has a pathway for patients to enter as high symptom, receive treatment, and improve - ending up in the low symptom group.  So the query pulls a single total engagement time median for low symptom patients who will ultimately step down but in the model that total engagement is split up into different time periods - first time to detect (which symptom group is the patient in?), followed by treatment and then step down decision - AND different patient pathways. The patients who improve and switch symptom category have a "time to improve" which obviously we can't pull from the data but is really important. So, possible solutions:

1. Just set a base time to improve ourselves, and point the teams to where it is in the parameters spreadsheet so that the team can change it if they want.
2. Re-use another part of the total engagement, such as the time to get stepped up or down after detection. 

Either way, we're going to have a bit of extra explaining to do, because we'll be (at least potentially) showing a total engagement in one place, and sub-engagements that sum up to more than that total elsewhere. This is expected though, because that overall total is a median, and it's reasonable to expect that these improvement pathway patients have above-average engagement.

Tom, anything to add or clarify? I'm not sure I fully captured the important details.

**Comment by jamesmrollins** [comment]
@holbrooa so this means that we are changing the training documentation and presentation to explain how time works in the model with relation to the patient's step up or down, but no model changes?

**Comment by TomRust** [comment]
Hi @jamesmrollins and @holbrooa -- 

Basically, yes, James.  Our proposals above are focused on better explaining how the data we have can be used to describe the patient pathways in the model, and *maybe* adding a feature in the data UI to allow teams to set their own basecase value for Time to Improve.  The most that will change in the model  diagram would be to swap the color of Time to Improve from red to green.  It will depend on what solution we decide on.

**Comment by jamesmrollins** [comment]
@holbrooa @TomRust  I don't plan to start working on this until Monday.  That will give you time to make decisions and I can submit a single "pull" to DEV (vs. piece-meal).

**Comment by TomRust** [comment]
As to your question @holbrooa , I think its pretty clear...maybe just clarifying that 

- Option 1 is what we currently have (where we have set a standard base case value for Time to Improve for all teams, and the teams can change them with the sliders); 
 - Option 2 is a team-specific base case value, based on some other piece of their team data (ie, we assume that the Time to Step up from the high-symptom stock (pulled from data) is the same as the Time to Improve down from that high-symptom stock (unknown)).  
 - There is also option 3 -- where the Data UI asks the team to estimate the Time to Improve for their setting, and that number becomes the base case value.  This option is more work for Andrew, but is the most transparent about how little data we have on Time to Improve.

**Comment by lzim** [comment]
Thanks @TomRust and @holbrooa for your work on this! 
FYI @jamesmrollins 

If I'm tracking this well enough, then...the combination of these two things continue to make the most sense to learners based on other features of the data UI and sim UI:

From @TomRust 
> * Option 2 is a team-specific base case value, based on some other piece of their team data (ie, we assume that the Time to Step up from the high-symptom stock (pulled from data) is the same as the Time to Improve down from that high-symptom stock (unknown)).

From @holbrooa 
> Re-use another part of the total engagement, such as the time to get stepped up or down after detection.
Either way, we're going to have a bit of extra explaining to do, because we'll be (at least potentially) showing a total engagement in one place, and sub-engagements that sum up to more than that total elsewhere. This is expected though, because that overall total is a median, and it's reasonable to expect that these improvement pathway patients have above-average engagement.

Consistent with our other _Modeling to Learn_ norms, I think it makes more sense to estimate from the team data (option 2) for the team in the data UI, explaining exactly how its estimated in the team data table "i." And then, adjust up/down from that base case value in the sim UI, clarifying in the slider "i," what they're changing when they adjust the slider (not the data UI, which is what I think option 3 is).

It would still be an experimental red variable for "read in" from team data. And, as always, any limits of estimating it a given way would need to be made explicit.

**Comment by branscombj** [comment]
@lzim @jamesmrollins @TomRust @dlkibbe @dlounsbu Would yall consider using a different icon for zooming out and zooming in than the + sign? Perhaps the square boxes that are used in the sim UI blue bars and in some browsers?

**Comment by TomRust** [comment]
@branscombj @jamesmrollins @dlkibbe @dlounsbu @lzim  -- I'm not married to the current icon we have for zooming in and out.

**Comment by TomRust** [comment]
@lzim , @holbrooa ,

Sorry I didn't remember this yesterday on our call -- SP currently actually has three different Times to Detect:
- in PC/PCMHI = 24 weeks 
- in GMH = 12 weeks
- in SMH = 4 weeks
These were set based on how often the average patient is seen in each setting.  I can change them to be the same across settings, if you wish.

**Comment by jamesmrollins** [comment]
Hi @branscombj  - what do you think about the below concept for expand?

![image](https://user-images.githubusercontent.com/30132017/55653479-8b4ee500-57a3-11e9-9bdc-0e2f26992609.png)

**Comment by branscombj** [comment]
@jamesmrollins I like it! Would this be the zoom out and for zoom in the arrow would point in? @lzim @TomRust @dlkibbe _Are y'all ok with this?_

**Comment by dlkibbe** [comment]
This makes sense to me. I like it @branscombj and @jamesmrollins

**Comment by lzim** [comment]
Thanks @jamesrollins

I like it too! And I agree with @branscombj it would be most consistent with other symbols if it pointed out for expansion/zooming out and in for zooming in.

**Comment by jamesmrollins** [comment]
@lzim @dlkibbe @branscombj   As you wish :-)  I'll put in tonight's pull.

**Comment by jamesmrollins** [comment]
Hi @jamesmrollins 

I was talking with @saveth and @holbrooa yesterday about the floors in the SP model, and we realized that we need to include an explanation of these floors in the itext of the Team Data Table.

Can you add these three pieces of text to their respective sections of the Team Data Table in the next dev pull?

1.	For Time to Improve: “This estimate is limited to a minimum of 12 weeks.”
2.	For Engagement Time Before Ending: “This estimate is limited to a minimum of 24 weeks.”
3.	For Engagement Time to Before Step Up/Down: “This estimate is limited to a minimum of 24 weeks.”
 
Thanks!
@TomRust

**Comment by jamesmrollins** [comment]
Hi @TomRust , @saveth and @holbrooa 

So if I interpret your instructions, the "i" text should read the following:

**Time to Improve**:   The additional time it takes high symptom patients to become low symptom patients calculated as the 75th percentile for engagement duration (weeks) minus the typical median engagement time (weeks) for all patients. The median engagement duration includes: time to detect, time to improve, time to stabilize and time to transfer. _This estimate is limited to a minimum of 12 weeks._ (wks)

**Engagement Time before Ending**: An estimate of the median time to quit for patients in each location, i.e. from when each patient starts with the location until their last visit. _This estimate is limited to a minimum of 24 weeks._ (wks)

**Engagement Time to Before Step Up/Down**:  An estimate of the median time with the referring location before a clean transfer. For patients who make a clean transfer, this calculation captures the time from the first visit to the last visit with the referring location before the first visit with the new team. Note that clean transfer patients can continue to see the referring team after the transfer, as long as the Return-to-clinic Visit Interval > 12 weeks. _This estimate is limited to a minimum of 24 weeks_. (wks)

Thanks,
James

**Comment by staceypark** [comment]
@jamesmrollins @branscombj @dlkibbe @TomRust 

@lzim was thinking this pop out for zooming out (and the arrow pointing the opposite way, or inward for zooming in) might be a clearer design? what do folks think?

![image](https://user-images.githubusercontent.com/31089501/55836643-fd8d3580-5ad3-11e9-86db-aac3654c13b8.png)

**Comment by TomRust** [comment]
@lzim @holbrooa @jamesmrollins --

Hi Andrew and Lindsey!  

I’ve been going over SP, and have some proposed itext changes for two experiment sliders and one variable in the Team Data Table.  I’d love your feedback before asking James to make any changes.

Experiment Section itext (additions in ***bold italics***):
1. High Symptom Patients % -- Set the % of patients who are found to be "high symptom." This value replaces the base case value estimated from team data. ***The BC value will likely differ from the value reported in the Team Data Table, as reported value is based on patient transfers after treatment, and this parameter represents the initial, currently unmeasured, distribution of patients’ initial symptoms before treatment.  This "initial symptoms proportion" BC value is calculated to produce the measured "final" symptom proportion seen in the data, given all other team data.***  

2. Time to Improve -- Set the amount of time it takes for the patients symptoms to change from "High" to "Low" in the same treatment setting. ***The BC value may differ from the value reported in the Team Data Table, as the initial estimate may conflict with the team's ability to maintain the symptom proportion estimated from team data.***


Team Data Table itext:

 3. Symptom Proportions % -- An estimate of the proportion of  patients who have high symptoms for that location, based on the proportion of patients who ***have*** step***ped*** up to a higher level of   care or risk during their engagement with that location. The model takes these ***known*** step up   proportions into account to determine ***the unknown*** initial symptom ***proportions*** and treatment effects for each location. (pct)

**Comment by saveth** [comment]
@TomRust you mentioned there are floors in the SP model.

•	Time to Improve (floor = 12 weeks)
•	Time to Recommend Step Up (floor = 24 weeks)
•	Time to Recommend Step Down (floor = 24 weeks)
•	Time to Residential (floor =24 weeks)

Apart from 'Time to Improve', I'm not seeing the same language you're using in the sim or ModelParameters file. Can you tell me which variables  they are mapped to in the ModelParameters or sim?

![image](https://user-images.githubusercontent.com/12439059/56611467-b8cec780-65c6-11e9-8e2a-4769a869caf8.png)

![image](https://user-images.githubusercontent.com/12439059/56611500-cbe19780-65c6-11e9-851c-0c4bf2192bfe.png)

**Comment by jamesmrollins** [comment]
Hi @saveth, below is the Team Data Table variable map.  Anything preceded by "data" is a direct upload from the ModelParameters file.

![image](https://user-images.githubusercontent.com/30132017/56614674-698c9500-65ce-11e9-861b-a029ac68164b.png)

**Comment by saveth** [comment]
@jamesmrollins Thanks for the image. Based on the variable map, it looks like it's pulling data directly from ModelParameters. Does this mean I don't need to be concern about coding a floor value to display in the Team Data Table?

**Comment by jamesmrollins** [comment]
@saveth  I believe that the first columns labeled "Time from Flag to Step Up/Down" may be the ones that are associated with the "Time to Recommend Step Up (floor = 24 weeks), Time to Recommend Step Down (floor = 24 weeks), Time to Residential (floor =24 weeks)." That isn't too clear because of the imprecise labels being used to express the floor values.  And yes, all data in the Team Data Table is derived from the Model Parameters file.  @TomRust will need to answer whether you need to display a floor value.

**Comment by lzim** [comment]
Hi @jamesmrollins 

Just got these interesting decimal values in **SP** with the **583ge_wl_bhip_2019_04_14.xlsx**  

![image](https://user-images.githubusercontent.com/7454688/56691223-44625a00-6694-11e9-8243-dd66342834cc.png)

**Comment by lzim** [comment]
Hi @jamesmrollins 

@TomRust @staceypark and I were just prepping some Sim UI runs in SP and we're seeing that it is not reading the uploaded data file properly. As you can see in the screenshot the .xlsx file downloaded from Epicenter is not what is displaying in the Team Data Table

![image](https://user-images.githubusercontent.com/7454688/56692825-e172c200-6697-11e9-8f26-cf73e518247b.png)

**Comment by staceypark** [comment]
@jamesmrollins following up from our conversation, @holbrooa  changes to the SP items in the Model Parameters files should not affect the sim. He is changing how the numbers are pulled in, not where they are.

**Comment by jamesmrollins** [comment]
That’s not true

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamesmrollins** [comment]
@lzim @TomRust @staceypark 
I haven't a clue why this new SP model is not working on Forio.  I have validated that the variables are named properly, that the data is loading from the 583ge_wl_bhip_2019_04_14.xlsx to the client version of Vensim correctly.  

However, when it loads to the model file in forio it is getting the data from outer space somewhere. The time clock is also haywire.  It should give a return indicating -1000 to 0 in groups of 100.  Instead it is running out past 3000, which explains the ultra low numbers we are getting in the SIM UI rate dials.

I think we have to adjust the clock somehow, which may solve the rate dial problem, but I am not sure why the data variables are not loading properly.  I will work with dev, but since the Forio Vensim model is producing these numbers, I am not sure we have the numbers.

More will be revealed.

**Comment by jamesmrollins** [comment]
@lzim @TomRust @staceypark 
I must have inadvertently deleted the SuicidePrevention_PROD.ctx file.  When I replaced it, the SIM UI returned to normal expected operation.  

So fixed . . . I think.

**Comment by staceypark** [comment]
@jamesmrollins Thanks for getting to the bottom of this!! 😄  looks to me like it's working now - I checked the team data table against the numbers in 583ge_wl_bhip_2019_04_14.xlsx and they look correct

@holbrooa @lzim @TomRust 
I'm noticing discrepancies in variable names between the data file and model params file. Some minor, but some I think can be confusing (i.e. step up/down vs. clean transfer)

I also noticed throughout we label the variables inconsistently units (weeks, percentage, etc.)  and measure of central tendency (mean, median, etc.). Sometimes, it's in the cell with the group name, sometimes with the variable name, or not at all.

Were we going to fix these after the more pressing fixes with queries? Or, did we decide to leave as is?
team data table | model params file 
--- | ---
new patient start rate | start rates
high risk patient flag rates | high risk flag rates
time to unflag high risk patients | time to unflag
engagement time before ending | engagement time before quit
time from flag to step up/down | time from flag to referral
engagement time before step up/down | engagement time before clean transfer

**Comment by lzim** [comment]
Thanks for your work on it @jamesmrollins !

**Comment by lzim** [comment]
@jamesmrollins Yes! I see the correct data file and the correct rounding of rates, etc. Thanks! 🏆

**Comment by lzim** [comment]
@jamesmrollins 

@TomRust and I are experimenting with SP.
**We see an issue: When you run your experiment in one setting, you can't access those runs in the results dashboard of another setting.**
- Runs are saved back to the world (team or individual).
- It makes sense that you can only view variables for a given setting in that settings Results Dashboard.
- And, when we run a GMH experiment, you do see the model diagram adjust values and you see the current run in the Outputs and Text and the Expanded Outputs sections. But, the Experiments (aka Alternative 1 and 2) are only viewable in the setting that you ran them.

**- All runs for all three settings should be available in the Control Panel for Alternative 1 and 2.**

PROBLEM Observed:
- Prior runs not available as alternative 1 and 2 in **_either_ Outputs and Text and the Expanded Outputs sections.**

**Comment by jamesmrollins** [comment]
Please define "session."  Is that an instance of the sim? I mean, are you saying that a player cannot see the experiments that a team lead can see?

**Comment by TomRust** [comment]
No, its not a Team Lead vs Player issue,  It's that after you run a few experiments with, say, GMH sliders, and you want to see how those experiments impacted care in PC or SMH, those previous experiments don't show up either in 1) the Control Panel drop down list or 2) the charts on the Results Dashboard in PC or SMH.

So, in the screenshot example below, we should have all our past experiments available in the drop down list (as they are when we're in the GMH Expanded Outputs section), but they aren't there at all in either PC or SMH Expanded Outputs sections. 

Also, when I select those alternate experiments from the Control Panel in GMH, then I switch over to PC or SMH, those alternative experiments no longer show up on the charts (either in Outputs or Expanded Outputs)

![image](https://user-images.githubusercontent.com/32961420/56777318-d22a6c00-679e-11e9-84fd-25b13ce99d4c.png)

**Comment by jamesmrollins** [comment]
AH!  Ok, that is indeed a limitation of the sim.  It can only display results within the setting view. So if you ran GMH and saved it as an experiment, it is bound to GMH and wouldn't be available in the PC/PCMHI or SMH setting view.

**Comment by TomRust** [comment]
Bummer!  There's no way to get the results into the other setting views?

**Comment by jamesmrollins** [comment]
Yes, you could run a concurrent session in another browser instance and run your alternatives there, minimize the windows and do side-by-side comparisons.

**Comment by dlkibbe** [comment]
@jamesmrollins @TomRust @lzim 
James, LZ & TR were reviewing the SP module today and noted the numbers available were a bit crazy -8000 etc. Thanks for review and correction.
![image](https://user-images.githubusercontent.com/31182258/56829093-d1dab100-6830-11e9-91da-070b5cfa8486.png)

**Comment by lzim** [comment]
@tomrust

Let’s think about how to address the setting view viewing constraint for our cybersem series.

Thanks @dlkibbe and @jamesmrollins

Specifically, James, what happened in Debbie’s screenshot was that we were trying to save an “implement measurement-based care” run, and when we selected that variable from the drop down the values for number reflect the patient load variable, not “none,” “partial,” and “full.”

**Comment by jamesmrollins** [comment]
@lzim @TomRust @dlkibbe  Thanks, problem noted.  Likely fixed by Monday.  I think the drop down is a fixed menu, but I will see about adding None, Partial and Full.  Seems likely.

**Comment by jamesmrollins** [comment]
@lzim @TomRust @dlkibbe 
The drop down issue is fixed, and the menu has been appended with "None, Partial and Full." These are available in PROD this morning.

**Comment by staceypark** [comment]
> AH! Ok, that is indeed a limitation of the sim. It can only display results within the setting view. So if you ran GMH and saved it as an experiment, it is bound to GMH and wouldn't be available in the PC/PCMHI or SMH setting view.

@lzim Where should I address this in the resources? sim cheatsheet and Facilitator SAY files?

**Comment by lzim** [comment]
@staceypark it needs to be clear everywhere

**Comment by staceypark** [comment]
@lzim @TomRust @dlkibbe @jamesmrollins 
I think the -8000 to 8000 drop down options were correct for SP, because this variable ranges that wide.
@TomRust Can you confirm?
![image](https://user-images.githubusercontent.com/31089501/56982560-76f9d000-6b36-11e9-8219-6da4bae9c605.png)

Also, I am in SP in PROD right now, and having issues with running & saving - When I change a Green None/Partial/Full slider (I tried GMH Implement MBC & GMH and SMH Implement Stepped Care) and then hit "Run" the sim is not registering the run.
1) Green slider bounces back to default
2) "Run" person icon is not grayed out. "Run" is still selectable while "Reset" is grayed out.
3) None of the output charts show any trend lines
4) When I save and recue up the experiment, there is no indication in the variable box that I made changes to the green sliders - still says None

**Comment by TomRust** [comment]
@staceypark @jamesmrollins  -- 

Hi Stacey, I don't understand your question...yes, a long time ago we decided that the min/max for "Manageable Total Patients" was going to be +/-8000.  I remember talking about changing it.

About running and saving in PROD...I don't know either!  I just ran that combined MBC+Stepped Care experiment you describe just fine in Chrome.  The SP model only works with these two data sets, because we change the format of the xlsx file to make it easier for a human to read:
-  583ge_wl_bhip_2019_04_14.xlsx
-  583ge_wl_bhip2_2019_04_14.xlsx

Were you using one of them?

**Comment by staceypark** [comment]
@TomRust @jamesmrollins 
On the -8000 to 8000 issue - following @dlkibbe comment, @jamesmrollins has revised the drop down to go from 0 to 100 instead of -8000 to 8000 because Debbie said it was an error. Was just confirming that the -8000 to 8000 range we had was indeed correct and that we need to switch back to that.

on the run issue - 
😅 okay was not using those files. I was using 100a1_abc_teama_2018_11_01.xlsx... No wonder things were wonky. Sorry!

**Comment by jamesmrollins** [comment]
@staceypark  - thanks for catching the -8000 to +8000 range issue.  I forgot completely about it, obviously. I hate correcting something that is correct - ugghhh!!

However, with that said, the drop down with |16,000| choices is going to be very, very long.  Therefore, I propose the following:

1.  When describing any 3 or 4 digit number, choose the numbers that make up that combination.  For example, if the number is 456, select "4" from the drop down and click on "Add."  Then select "56" from the drop down and click on "Add."  The result will look like this -  "4_56."    
2.  This could also work for larger numbers.  "6790" could be created by selecting "67" and then "90" which would create "67_90."

Or I can give you a range from -8000 to 8000.  

@lzim  - Let me know and I will be happy to make the changes.

**Comment by lzim** [comment]
@jamesmrollins @TomRust @holbrooa 

Issue James and I just observed with Manageable Total Patients in SP GHM Setting View

![image](https://user-images.githubusercontent.com/7454688/57004622-370e0980-6b85-11e9-93c4-22138a4ad1b8.png)

**Comment by lzim** [comment]
@jamesmrollins @TomRust @holbrooa

Some other interesting bc values

![image](https://user-images.githubusercontent.com/7454688/57004730-12fef800-6b86-11e9-9b21-8b675a850cbb.png)

**Comment by lzim** [comment]
@jamesmrollins 

SP Decision for Save Dialogue

None
Partial
Full
8000
0
-8000

**Comment by jamesmrollins** [comment]
@lzim the drop down has been fixed.  We had a version mis-match problem between TEST and PROD that created the errors we saw last night, and you documented above.

**Comment by lzim** [comment]
@jamesmrollins and @TomRust 

Okay, thanks James. I'll be reviewing PROD in couple hours for SP.

**Comment by lzim** [comment]
@jamesmrollins and @TomRust 

Need to make sure all these fixes are looking good in DEMO PROD and SIM PROD

FYI: @staceypark

**Comment by TomRust** [comment]
@jamesmrollins @lzim @branscombj --

 I can't replicate your crazy BC values...Are you sure you were using the 4-14 bhip data set?

![image](https://user-images.githubusercontent.com/32961420/57046746-ab0ce800-6c3f-11e9-8094-b8d2acb3a8cc.png)

**Comment by jamesmrollins** [comment]
@TomRust @lzim  Yes, I agree with Tom.  It appears to run ok with me as well.

**Comment by TomRust** [comment]
@jamesmrollins -- Could you push these changes to the wording of the itext for the Team Data Table and Experiment Section?

Experiment Section itext (additions in bold italics):Experiment Section itext (additions in ***bold italics***):
1. High Symptom Patients % -- Set the % of patients who are found to be "high symptom." This value replaces the base case value estimated from team data. ***The BC value will likely differ from the value reported in the Team Data Table, as reported value is based on patient transfers after treatment, and this parameter represents the initial, currently unmeasured, distribution of patients’ initial symptoms before treatment.  This "initial symptoms proportion" BC value is calculated to produce the measured "final" symptom proportion seen in the data, given all other team data.***  

2. Time to Improve -- Set the amount of time it takes for the patients symptoms to change from "High" to "Low" in the same treatment setting. ***The BC value may differ from the value reported in the Team Data Table, as the initial estimate may conflict with the team's ability to maintain the symptom proportion estimated from team data.***


Team Data Table itext:

 3. Symptom Proportions % -- An estimate of the proportion of  patients who have high symptoms for that location, based on the proportion of patients who ***have*** step***ped*** up to a higher level of   care or risk during their engagement with that location. The model takes these ***known*** step up   proportions into account to determine ***the unknown*** initial symptom ***proportions*** and treatment effects for each location. (pct)

**Comment by jamesmrollins** [comment]
@TomRust  Consider it done.

**Comment by lzim** [comment]
Glad to hear of this lack of replication @jamesmrollins and @tomrust

**Comment by lzim** [comment]
![gmh_new_pt_new_episode6](https://user-images.githubusercontent.com/7454688/57172179-5f8a4380-6dd1-11e9-8106-8c14462120e3.png)
![gmh_new_pt_new_episode5](https://user-images.githubusercontent.com/7454688/57172180-5f8a4380-6dd1-11e9-8531-5bbd440cf680.png)
![gmh_new_pt_new_episode4](https://user-images.githubusercontent.com/7454688/57172181-6022da00-6dd1-11e9-9150-a453271498e3.png)
![gmh_new_pt_new_episode3](https://user-images.githubusercontent.com/7454688/57172182-6022da00-6dd1-11e9-92c6-cb6920695d3f.png)
![gmh_new_pt_new_episode2](https://user-images.githubusercontent.com/7454688/57172183-6022da00-6dd1-11e9-8e30-2b82ff6aa0b8.png)
![gmh_new_pt_new_episode1](https://user-images.githubusercontent.com/7454688/57172184-6022da00-6dd1-11e9-8af7-09c53087b31f.png)

**Comment by lzim** [comment]
@jamesmrollins @TomRust and @holbrooa 

Thanks Everyone for working on this!

I expect James needs the format in the Word document in order to hand to DEV. I annotated the Word document, but when notes were more extensive, I provide tables of my recommended edits and notes to make it clearer (below). I pointed to GitHub with Word Comments when I recommend something other than the edits in v2 James circulated this morning w/"lz" in the filename.

I caught a few more things below than in the Word document.

Thanks!

Lindsey

**Overall notes:** 
1. It seems better to describe the 9 month default threshold for "new" (NOTE: we intend for the user to be able to override this, however...) than to try to retain "clean transfer" and other such language. It is clearer for the clincian/learner to just read the gap in weeks.
2. Keep an eye for using "setting" or "location" for consistency. Since we call it the "Setting View" probably need to go with "setting," as our primary descriptor.*


**FIRST SCREENSHOT**

Old Name | New Name | Correct Units | Location | New Defintion | Notes
-- | -- | -- | -- | -- | --
New Patient Start Rate (mean) | New Care Episode Start Rate | (pts/wk) | Team Data Table | An estimate of the new care episode start rate, comprising patients starting a new episode of care after receiving no care in that setting within the last nine months. | *Cannot simply use new "episode" because it will be confused with a new episode of a clinical presenting concern, e.g., "depression" "psychosis."
New Patient Wait Time (median) | New Care Episode Wait Time | (wks) | Team Data Table |   | *Need definition in the Team Data Table "i." Recommend Andrew helps.


![gmh_new_pt_new_episode1](https://user-images.githubusercontent.com/7454688/57198666-3f21cc80-6f2a-11e9-8f46-49dcb2e31976.png)

**SECOND SCREENSHOT**

Old Name | New Name | Correct Units | Location | New Defintion | Notes
-- | -- | -- | -- | -- | --
GMH New Patient Start Rate |   | pts/wk | Experiments/Slider | Set the number of patients recommended to start care in this setting each week. This value replaces the base case value estimated from team data. | *1. For "i" information. Just added the word "care" after start. 2. Change in PC/PCMHI & SC too.
Wait Times (wks) |   | (wks) | Team Data Table | An estimate of the median wait time for each care transfer to another care setting. This calculation captures the gap from the referring care setting (last visit) to the destination care setting (first visit). Note that patients can continue to see the referring team after the transfer, as long as the Return-to-clinic Visit Interval > 12 weeks. (wks) | *Removed "clean transfer" language.

**Recommended header text (for screenshot below): "GMH Patients Waiting to Start GMH Care."**

![gmh_new_pt_new_episode2](https://user-images.githubusercontent.com/7454688/57198737-38478980-6f2b-11e9-9f65-b9771b05642b.png)

**THIRD SCREENSHOT - LZ edits to convey "from referring setting consistent with description in "i" information **

Old Name | New Name | Correct Units | Location | New Defintion | Notes
-- | -- | -- | -- | -- | --
GMH Openings for New Patients % | GMH Openings for New Care Episodes %  | % | Experiments/Slider | _See notes to the right; **for an issue in the PC/PCMHI setting view, even tho screenshot is GMH_** | *"i" information label correct, but definition describes with "PC/PCMHI Openings for GMH"
PC/PCMHI Openings for GMH % | GMH Openings for New Care Episodes from PC/PCMHI % | % | _PC/PCMHI Experiments/Slider_ | _See notes to the right; **for an issue in the PC/PCMHI setting view, even tho screenshot is GMH_** | *"i" information label correct, but definition describes with "PC/PCMHI Openings for New Patients"
GMH Openings for SMH % | GMH Openings for New Care Episodes from SMH % | % | Experiments/Slider   |   |

![openings_for](https://user-images.githubusercontent.com/7454688/57198962-23202a00-6f2e-11e9-90c4-b8f2130a2cc7.png)

Old Name | New Name | Correct Units | Location | New Defintion | Notes
-- | -- | -- | -- | -- | --
GMH Sensitivity of Start Rate to Wait Time | keep old name | 0-2 | Experiments/Slider |   | *Clinical rationale for "i" information first sentence needs to be provided: "Initially set to "1," where if the wait time doubles, then the start rate is doubled…as clinicians perce
GMH Sensitivity of Start Rate to Patient Load | keep old name | 0-2 | Experiments/Slider |   |

**Comment by jamesmrollins** [comment]
@lzim @TomRust @holbrooa Changes are up in the TEST environment.  Besides a few line justification issues, all requested changes are present.  Let me know if you need any further adjustments.  If no other feedback, I will promote to PROD tonight.  Thanks ~ James

**Comment by TomRust** [comment]
@jamesmrollins -- Looks great!
Two things:


1) Suggestion for the itext for the slider for "___ Openings for New Care Episodes %":  _Set the % of total openings to be used by patients starting a new episode of care not coming from either PC/PCMHI or SMH settings. This value replaces the base case value estimated from team data._

2) Also, could we get the summing widget to always show the total, not just of the values that deviate from the base case?  So, for the screen shot below, instead of the total reading 7 when one slider is at 7, the total would read 106% and show the warning?

![image](https://user-images.githubusercontent.com/32961420/57249861-0cec9980-7014-11e9-9a5a-f15976aac73d.png)

**Comment by TomRust** [comment]
@jamesmrollins @lzim -- 

About GMH Sensitivity of Start Rate to Wait Time itext:  How about this?

 "Initially set to "1," where ***the team is sensitive to how long patients are waiting to start a new episode of care, specifically, the team will increase the start rate directly as the wait time increases above their desired wait time (i.e., if the wait time doubles, then the team doubles the start rate, too).*** Lowering the sensitivity to "0.5" will reduce the effect (if wait time doubles, then the start rate only increases by ~40%), and increasing the sensitivity to "2" will increase the effect (if wait time doubles, then the start rate increases by ~300%).

**Comment by jamesmrollins** [comment]
@TomRust No problem on the "i" text you request above.  I will get those into the model-popup-information file.  Regarding displaying values and summing on the widget, what you are asking for is not possible, because they are set to default at -.01.  The values shown in the BC pop ups are not available until the sim reaches t=0.

**Comment by TomRust** [comment]
@jamesmrollins -- I don't get it.  Isn't the model at t=0 by the time the UI loads for the user, so aren't those values available?  by the time the user would move the slider and need to see them sum to 100%?

**Comment by jamesmrollins** [comment]
@TomRust they are available, but after the code has completed running and cannot do anything else until selected by the user.  Something like this:

1.  User selects play.
2.  Sim UI code loads vensim model 
3.  Model reads user switch defaults.
4.  Calculate to t=0
5.  Stop.

**Comment by jamesmrollins** [comment]
@TomRust hey, wait a minute.  Perhaps we could make a "Set to BC" button.  It would then read the BC values and set up the switch.  Kind of like how the sim loads prior experiments and sets the sliders.

**Comment by TomRust** [comment]
@jamesmrollins -- Maybe... I do like it, but am wary of creating anything else that the user must do before running a sim.

**Comment by jamesmrollins** [comment]
@lzim @TomRust @holbrooa 
- Label changes moved to PROD
- @TomRust requested switch modification available in TEST. If satisfied with functionality, please indicate here and I will promote to PROD.

**Comment by lzim** [comment]
@jamesmrollins @dlkibbe @TomRust 

Recevied an issue via email. Moved it here for tracking.
![0509191551_resized](https://user-images.githubusercontent.com/7454688/57561237-6409ab80-733f-11e9-8eac-0eaa323808a7.jpg)

This is the display resolution of my VA machine, which I am using to present.
![image](https://user-images.githubusercontent.com/7454688/57561283-b2b74580-733f-11e9-8684-94b987d8ad18.png)

**Comment by branscombj** [comment]
@TomRust Is this i text wrong - should it say 
![image](https://user-images.githubusercontent.com/29778290/57731689-3e471400-7669-11e9-8547-68b72bf25eb6.png)

**Comment by branscombj** [comment]
@TomRust  I'm confused about this loop, which says it's about quality, but I don't see it connected to any quality variables. I think another thing that's confusing me in this loop and the one in the above comment is the variable "Patient Load". To me, that name sounds like a stock - the total number of patients in care. But here it is defined as the number recommended. Would it make sense to call it "SMH Patients Recommended to Start"?


SMH Effect of Patient Load on Manageable Total Patients
As workload increases, the **quality of care provided by a team**decreases, and vice versa. This effect is limited to 2x, as even the lowest workload could no more than double the original quality of care (i.e., no more than halve the current **Time to Improve and the Time to Unflag**).

![image](https://user-images.githubusercontent.com/29778290/57732778-d47c3980-766b-11e9-8365-dbb5c90c28de.png)

**Comment by lzim** [comment]
@jamesmrollins @TomRust 

We found that the Save Dialogue for SP was not saving the selected variable name. We believe we reproduced the error in team and individual worlds a couple times, between Tom and I.

1. Screenshot 1 - Select MBC
![mbc_1](https://user-images.githubusercontent.com/7454688/57742329-93892280-7675-11e9-9bf6-1cd05d8b4397.png)

2. Screenshot 2 - Confirmed MBC Selection
![mbc_3](https://user-images.githubusercontent.com/7454688/57742353-ab60a680-7675-11e9-98e5-f61279a32619.png)

3. Screenshot 3 - Resulting name **"GMTP – GMH Manageable Total Patients"** not **"GIM – GMH Implement MBC"**
![mbc_3](https://user-images.githubusercontent.com/7454688/57742366-b9162c00-7675-11e9-95ae-470f01f69bb9.png)

4. Screenshot 4 - It only happened the first time.
![mbc_4](https://user-images.githubusercontent.com/7454688/57742501-35107400-7676-11e9-967a-cb4aae240672.png)

5. Screenshot 5 - On a second selection it displayed **"GIM"** when selected.
![mbc_5](https://user-images.githubusercontent.com/7454688/57742518-40fc3600-7676-11e9-8ebb-e5b4da7e9a4f.png)



**Holla @staceypark for the "Help" section that helped us figure it out. 🙌

**Comment by jamesmrollins** [comment]
@lzim @TomRust  Yes - I was able to reproduce this problem.  It seems to happen on the initial attempt to save, then corrects after that.  In any case, we are on it . . .

**Comment by lzim** [comment]
Howdy @jamesmrollins 👋 

1. I'm getting this error at mtl.how/team:
![mtl how_team](https://user-images.githubusercontent.com/7454688/57750732-3e123d00-7698-11e9-8fb5-b26b0c8f4138.png)

2. I also find that if I need to rename experiments the little progress animation by the save button will keep moving for >5 min. without exiting, unless I refresh the window or hit the "x" to close. It did save when I initiated an exit, but the animation implies it's still working on the change.
![save_8 35 03 PM](https://user-images.githubusercontent.com/7454688/57750760-5bdfa200-7698-11e9-9686-bb84b511eede.png)

**Comment by jamesmrollins** [comment]
Forio’s server was down. I reported it. Should be ok now.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by lzim** [comment]
@jamesmrollins 

In a team meeting now, mtl.how/team is still not up 🙁

**Comment by jamesmrollins** [comment]
mtl.how/team is currently programmed to:
https://forio.com/app/va/va-psd-demo/teampsd.html

We need to reprogram the addresses:

For TEAM PSD website:
https://forio.com/app/va/va-psd-team/teampsd.html

For MLT Demo website:
https://forio.com/app/va/va-psd-demo/mtl_demo.html

This change is the result of splitting the two websites into their own environments.  If possible, give me the information for mtl.how and I can ensure that I keep it up to date.  

Sorry for the inconvenience.

James

**Comment by jamesmrollins** [comment]
The screen resolution error at 1280 is corrected. 

The experiment naming issue identified above has been resolved.

**Comment by lzim** [comment]
@jamesmrollins 

Thanks, just let me know if the URLs change and I can update the co-branded links.
Updated mtl.how/team

**Comment by lzim** [comment]
@jamesmrollins @TomRust 

@branscombj Noted 6 days ago that there was an issue in the SMH setting view
> Is this i text wrong - should it say patient load instead of wait times in the first sentence? I don't see a "waiting to start" variable. 

We see that you checked in an updated **master_crosswalk_workflow** on Friday https://osf.io/ygp36/. 

But, today we are still seeing "i" information (on OSF here: https://osf.io/svrpn/ in the SMH Setting View that do not match

**_James, will you please take a look at what may be causing this discrepancy?_**

![image](https://user-images.githubusercontent.com/7454688/58042850-43093d80-7b2b-11e9-8726-c7c073d66b58.png)

**Comment by lzim** [comment]
Question for @jamesmrollins and update for @saveth and @staceypark 

1. @jamesmrollins @holbrooa and I have edits for the OSF **model-popup-information.xlsx** file in OSF, but we don't know if we should upload it to OSF to replace this file https://osf.io/svrpn/ and then upload to Epicenter given the issue above discovered by @branscombj showing mis-match of pop-ups with SMH. **@jamesmrollins Please advise if you are looking into the mis-match issue. We would like to move forward with these SPParams edits before our Wed training session.**

2. Andrew and I did update the **ModelParameters.xlsx** on OSF here: https://osf.io/j3ubz/
@saveth The updated file can be used to update the tt reports for SP. @staceypark this needs to be updated at mtl.how

_NOTE to all: We have NOT yet updated column E of the SPParms tab in the Data UI or the Team Data for Sim UI._We plan to have that last edit done tomorrow, but it does not impact the Sim UI or the tt reports the way the updated column D does.

Thanks!

FYI: @TomRust @branscombj @dlkibbe @dlounsbu

**Comment by jamesmrollins** [comment]
Hi @lzim.  I did attempt to identify the model pop-up mismatch.  However, I don't think I correctly understand the problem, as I was not able to locate any errors. In other words, the "i" information associated with the variable you show above, is indeed what is in the model-popup-information file.

I did call and talk to @branscombj , and she indicated her issue was something different.  

I have a call out to @TomRust to discuss, waiting for return call.  I would go ahead and update OSF.  When I get to the bottom of the problem (hopefully first thing tomorrow morning), then I can make corrections and migrate it to Epicenter.

James

**Comment by lzim** [comment]
Thanks @jamesmrollins 

@TomRust @branscombj  and I crafted my first message on this issue today together. We realized what @branscombj was questioning was due to the fact she was getting incorrect pop-ups in SMH setting view.

I'm meeting with @TomRust pretty early in the AM our time (6:30AM Pacific). Given that the **model-popup-information.xlsx** and the Sim UI correspond, we may need help from @TomRust to get to the bottom of it. At the same ...

- ... to be clear, **the correct "i" information is displaying for GMH setting view.** It is the SMH and PC/PCMHI setting view pop-ups that are not correct and are not consistent with GMH setting view.

@holbrooa It sounds like you can go ahead with taking our Column D SPParams edits across the setting views in **model-popup-information.xlsx** by checking it out, adding our edits and checking back in. Then, @jamesmrollins, I or one of our other Team PSD co-faciltators can then upload to Epicenter. 

- Ideally @TomRust and @holbrooa can also talk about the issue of "User-defined threshold" rows in the updated **ModelParameters.xlsx** file in the AM before Tom and I meet at 6:30AM and Andrew and I meet at 11AM (Pacific times).

- We want to get the updates in to Epicenter and the updated **Column E information for our "wl_bhip" Data UI, and Team Data Table, for Sim UI on the Sharepoint**, and updated in **ModelParameters.xlsx** in OSF tomorrow so we can be ready for our **session 3 training with the TAS on Wednesday** :smile:

Thanks All! 

FYI @staceypark @saveth @dlkibbe @dlounsbu

**Comment by jamesmrollins** [comment]
@lzim @branscombj @TomRust 

Not sure how such a mess got created, but the model-popup-information has been sorted out.  I had to work some naming-conventions changes back to the model, so I am going to limit the next update to TEST so I can ensure the model-variable-pop up information align and work properly.  Once everything checks out in TEST tomorrow morning, then I will promote to PROD Wednesday night. I will post the team data table mark-ups later this afternoon.  When everything is promoted to PROD, then I will update OSD with model-popup-information and model_crosswalk.

**Comment by jamesmrollins** [comment]
Team Data Table Mark-up

![image](https://user-images.githubusercontent.com/30132017/58127065-57037c80-7bc9-11e9-86ff-7c79f36791d4.png)

**Comment by lzim** [comment]
@jamesmrollins @holbrooa 

**Two minor Sim UI updates for the ModelParameters.xlsx file that James has checked out and that is going to DEV** 

1. Remove (median) from Time to Improve variable name in Team Data Table.

2. Edit the description for symptom % to change "patients" to "care episodes"

**Comment by TomRust** [comment]
@jamesmrollins @lzim -- We just tried to run an experiment where we implement Measurement Based Care in both GMH and PC/PMCHI (move one green slide in each setting to full).  We were unable to have both sliders at "full" at the same time.  Switching from GMH to PC setting views to access the PC slider reset the slider in GMH.  

It would be great if we could run experiments across settings!!!  :-)  Any way we can work around this unwanted reset?

**Comment by jamesmrollins** [comment]
Hi @TomRust and @lzim , we are exploring the inter-session analysis need.  Since each setting is a different page, the browser can only handle one-at-a-time.  So without a serious re-engineering, I'm not sure we can accommodate this design need.  More will be revealed . . .

**Comment by TomRust** [comment]
@holbrooa & @lzim  -- 

For Q#1 - I propose a third option to maximize the number of flag transfers we'd identify in the data -- count all possible flag transfers from PC and SMH to GMH as _clean_ transfers to GMH (even if in any other circumstance they would be classified as concurrent).  For such small numbers, I'm wary of inflating the number of people with a high risk flag (as concurrent transfers do), especially when there is no way in the model for patients to start new to a setting with a flag (they can only gain a flag after they are identified as high symptom, or get a flag elsewhere and transfer into GMH).  I don't want PC and SMH to appear to be keeping their flag patients for a very long time, just because they concurrently transferred them to GMH instead of clean transferring them.

**Comment by holbrooa** [comment]
@TomRust @lzim 

That makes sense - I totally see where you're coming from. The details are complicated though, so to implement that correctly, I think I'll need you on the phone to walk through it together.  I'm doing some work to get an idea of the ramifications.

**Comment by jamesmrollins** [comment]
@TomRust @lzim regarding the ability to view experiments across settings:

1.  It is now possible in TEST to view an experiment saved for one setting, in another setting view.  For example, if a GMH experiment is saved, the SMH and PC/PCMHI results can be viewed in their respective settings.  
2.  The export file now contains all setting's values from model variables. 

I have run a few experiments and have validated that experiments are view-able in each setting view.  However, I encourage users to experiment on their own to ensure we have it right. When I get a thumbs up, I will promote to PROD.

Thanks,
James

**Comment by staceypark** [comment]
@jamesmrollins to clarify on point #2, Do you mean that cell values have shifted or added? Or is it that the cells have stayed the same and whereas previously we only got one setting at a time with other setting values at 0/BC, now we can just get all the values in one export?
fyi @saveth

**Comment by jamesmrollins** [comment]
@saveth @staceypark  Yes, you are correct.  Before the SIM UI would only save the values from the variables of the chosen setting.  Now the export file contains the values from the other two settings.  For example, I saved an experiment from a simulation run in the GMH setting.  When I export, I will see values for GMH, SMH and PC/PCMHI.  In the previous version, I would have only seen GMH values.

**Comment by TomRust** [comment]
It looks like the new feature works here:
![image](https://user-images.githubusercontent.com/32961420/58644907-455c5c00-82d0-11e9-89c7-59644fabf4b0.png)

but not here:
![image](https://user-images.githubusercontent.com/32961420/58644943-5907c280-82d0-11e9-814f-e7bd792dc5fc.png)

Sorry for not being able to show the differences in the drop-downs via screenshot.  In all three settings, the red "Select Previous Experiment to Set Experimental Values to a Former State" drop down has all past experiments and the experiments I ran today in test in different settings, but the blue "Select Experiment Alternative 1" drop down doesn't show either past experiments or experiments run today in test in different settings.  That blue dropdown list only shows experiments that were saved in that setting (even if the actual experiment slider was in a different setting).

**Comment by TomRust** [comment]
Hi @jamesmrollins !  Actually, I was in PROD, not test (duh!).  I just tested the new feature in TEST, and it all works perfectly.  Both dropdown lists have all the past experiments, regardless of setting.

**Comment by TomRust** [comment]
@jamesmrollins  --  I finally got the a screenshot of the "page unresponsive" pop-up in Chrome.

![image](https://user-images.githubusercontent.com/32961420/58658739-2a4d1480-82ef-11e9-9203-b14812c8dead.png)

**Comment by jamesmrollins** [comment]
@TomRust Yeah, that is just a result of a very large load-up time.  Just click "Wait" and it will load.

**Comment by TomRust** [comment]
@jamesmrollins -- right.  I thought you wanted a screenshot of the  "page unresponsive" pop-up ... to bring it up with Forio...or maybe it was @lzim or @branscombj who wanted one, so it could be included in the training materials for session 5?

**Comment by jamesmrollins** [comment]
@TomRust  Right! Right!  Yes, I did want it to confirm it was what I thought it was.  So yes, thank you.  I will bring it up with Forio, although the problem likely rests with Ventana, as it is their enterprise service (Linux) software that loads the model.

**Comment by lzim** [comment]
@jamesmrollins @tomrust and @staceypark

And, I wanted a screenshot to include in our guides/cheatsheets so that folks know what to do if they see it.

**Comment by saveth** [comment]
@jamesmrollins there were a lot of changes to the SIM UI and ModelParameters (small things like variable names, order, etc.) that drastically changed my R code for the tt report. These changes are now captured.

**Comment by jamesmrollins** [comment]
Thanks @saveth !  
Unless there are objections, I will promote this iteration to PROD on Monday.

Thanks,
James

**Comment by lzim** [comment]
@jamesmrollins Can this issue be closed?

I'm looking at all the issues under the 1.8 Sprint Milestone and hoping that they can be closed.
Thanks!
🏃‍♀

FYI: @staceypark

**Comment by jamesmrollins** [comment]
@lzim yes, this can be closed.
